name: fire_chat_app
description: Aplicación de chat con firebase.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # Dependencias
  intl: ^0.16.1

  image_picker: ^0.6.7+22

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - lib/assets/images/
